version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: build/Dockerfile
    container_name: kafka-dbreplication-app
    environment:
      - APP_ENV=prod
      - DB_PASSWORD=apppassword
    depends_on:
      - mysql-master
      - mysql-slave1
      - mysql-slave2
      - mysql-slave3
    networks:
      - kafka-db-network
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  kafka-db-network:
    external: true
    name: kafka-dbreplication-go_kafka-db-network